// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "a67d27ae-171c-49ea-9cf0-452ca4a3d991";
const char DEVICE_LOGIN_NAME[]  = "96b7daca-0e03-49db-88a2-8304ae6fa1b7";

const char SSID[]               = "Fibertel WiFi514 2.4GHz";    // Network SSID (name)
const char PASS[]               = "0043106872";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "EW3CXGLMDZUWTSSBUKWH";    // Secret device password

CloudLength distance;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(distance, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
